### ISSUE TITLE
Cannot `require` fairmont from REPL

### ISSUE THREAD

**Issue by PandaWhisperer** [pandastrike/fairmont#23]
I'm getting an error whenever I try to `require` fairmont (1.0.0-alpha-04) from the CoffeeScript REPL, or any code that requires fairmont. See example:

```
$ coffee --nodejs --harmony

coffee> require "fairmont"
/Users/chris/Code/temp/node_modules/fairmont/lib/helpers.js:7
  if (script.match(/test.litcoffee$/)) {
            ^
TypeError: Cannot read property 'match' of undefined
  at Object.<anonymous> (/Users/chris/Code/temp/node_modules/fairmont/lib/helpers.js:7:13)
  at Object.<anonymous> (/Users/chris/Code/temp/node_modules/fairmont/lib/helpers.js:27:4)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/Users/chris/Code/temp/node_modules/fairmont/lib/index.js:5:10)
  at Object.<anonymous> (/Users/chris/Code/temp/node_modules/fairmont/lib/index.js:105:4)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at repl:1:5
  at Object.exports.runInThisContext (vm.js:74:17)
  at REPLServer.replDefaults.eval (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/repl.js:46:42)
  at bound (domain.js:254:14)
  at REPLServer.runBound [as eval] (domain.js:267:12)
  at repl.js:279:12
  at REPLServer.<anonymous> (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/repl.js:79:9)
  at REPLServer.emit (events.js:129:20)
  at REPLServer.Interface._onLine (readline.js:214:10)
  at REPLServer.Interface._line (readline.js:553:8)
  at REPLServer.Interface._ttyWrite (readline.js:830:14)
  at ReadStream.onkeypress (readline.js:109:10)
  at ReadStream.emit (events.js:129:20)
  at readline.js:1175:14
  at Array.forEach (native)
  at emitKeys (readline.js:993:10)
  at ReadStream.onData (readline.js:910:14)
  at ReadStream.emit (events.js:107:17)
  at readableAddChunk (_stream_readable.js:163:16)
  at ReadStream.Readable.push (_stream_readable.js:126:10)
  at TTY.onread (net.js:529:20)
```

Same thing happens from the `node` REPL:

```
$ node --harmony
> require("fairmont")
TypeError: Cannot read property 'match' of undefined
    at Object.<anonymous> (/Users/chris/Code/temp/node_modules/fairmont/lib/helpers.js:7:13)
    at Object.<anonymous> (/Users/chris/Code/temp/node_modules/fairmont/lib/helpers.js:27:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/chris/Code/temp/node_modules/fairmont/lib/index.js:5:10)
    at Object.<anonymous> (/Users/chris/Code/temp/node_modules/fairmont/lib/index.js:105:4)
```

Here's my version of `lib/helpers.js`:

``` coffeescript
// Generated by CoffeeScript 1.8.0
(function() {
  var Amen, assert, script;

  script = process.argv[1];

  if (script.match(/test.litcoffee$/)) {
    assert = require("assert");
    Amen = require("amen");
    module.exports = {
      assert: assert,
      describe: function() {
        return Amen.describe.apply(Amen, arguments);
      }
    };
  } else {
    module.exports = {
      assert: function() {},
      describe: function(string, fn) {
        return fn({
          test: function() {}
        });
      }
    };
  }

}).call(this);
```

It looks like `script = process.argv[1]` is not being tested for `undefined`, despite [helpers.litcoffee](https://github.com/pandastrike/fairmont/blob/master/src/helpers.litcoffee) showing `script?.match`. 

Perhaps republishing will fix this?

**Comment by PandaWhisperer** [comment]
Update: as of version 1.0.0-alpha-09, this no longer seems to be an issue.
