### ISSUE TITLE
Compiled version tries to import from coffeescript path

### ISSUE THREAD

**Issue by Lacrymology** [pandastrike/fairmont#41]
```
> require('fairmont')
Error: Cannot find module '../src/index'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /home/lacrymology/workspace/panda/photokharma/photokharma-fre-node/node_modules/fairmont/lib/iterator.js:280:12
    at module.exports.describe (/home/lacrymology/workspace/panda/photokharma/photokharma-fre-node/node_modules/fairmont/lib/helpers.js:20:16)
    at Object.<anonymous> (/home/lacrymology/workspace/panda/photokharma/photokharma-fre-node/node_modules/fairmont/lib/iterator.js:20:3)
    at Object.<anonymous> (/home/lacrymology/workspace/panda/photokharma/photokharma-fre-node/node_modules/fairmont/lib/iterator.js:474:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

A quick look at the tree shows that at `../src` there're the coffeescript files, and the javascript files live in `../lib`.

I don't know the correct solution for this, I'm new to coffee

**Comment by PandaWhisperer** [comment]
That's an error in [`iterator#assoc`](https://github.com/pandastrike/fairmont/blob/master/src/iterator.litcoffee#assoc).

Changing the first line to `require "./index"` makes it work.

**Comment by dyoder** [comment]
I've already fixed this.
